.gitignore, README.md, gemviz23/app.py, gemviz23/hello.ui
=> Create a simple PyQt app that loads & shows a .ui file

gemviz23/demo/LICENSE, gemviz23/demo/aboutdialog.py, gemviz23/demo/app.py, gemviz23/demo/filterpanel.py, gemviz23/demo/mainwindow.py, gemviz23/demo/resources/aboutdialog.ui, gemviz23/demo/resources/filterpanel.ui, gemviz23/demo/resources/mainwindow.ui, gemviz23/demo/resources/textwindow.ui, gemviz23/demo/resources/tiledserverdialog.ui, gemviz23/demo/textwindow.py, gemviz23/demo/tiledserverdialog.py, gemviz23/demo/utils.py
- close #17
Main window (built from a ui file) adds additional content from another ui file.  Application uses the menu bar and provides an `About ...` dialog (modeless). 
The About box has two pushbuttons that launch a web browser to show a specific URL.  A third pushbutton brings up a new dialog showing the full text of the software license.
=> examples of multiple windows

.gitignore, gemviz23/result_function.py, gemviz23/ui_files/filter_window_version2.ui, gemviz23/ui_files/result_window.ui, gemviz23/ui_files/result_window_table_widget.ui, gemviz23/ui_files/table_window.py
=> display filter runs in table 

gemviz23/demo/mainwindow.py, gemviz23/demo/resources/filterpanel.ui, gemviz23/demo/resources/mainwindow.ui
=> refactor mainwindow to storyboard

gemviz23/demo/mainwindow.py
=> Use .exec() instead of .show()

gemviz23/demo/aboutdialog.py, gemviz23/demo/app.py, gemviz23/demo/filterpanel.py, gemviz23/demo/mainwindow.py, gemviz23/demo/resources/resultwindow.ui, gemviz23/demo/resultwindow.py, gemviz23/demo/textwindow.py, gemviz23/demo/tiledserverdialog.py, gemviz23/demo/utils.py
=> formatting adding results table ui 

gemviz23/demo/resources/filterpanel.ui
=> integrate filter UI into demo app #30

gemviz23/demo/filterpanel.py, gemviz23/demo/mainwindow.py, gemviz23/demo/resources/filterpanel.ui, gemviz23/demo/utils.py
=> connect server, choose catalog, start filtering #35

gemviz23/demo/date_time_range_slider.py, gemviz23/demo/filterpanel.py, gemviz23/demo/range_slider.py, gemviz23/demo/resources/date_time_range_slider.ui, gemviz23/demo/resources/filterpanel.ui, gemviz23/demo/resources/resultwindow.ui, gemviz23/demo/tiledserverdialog.py, gemviz23/demo/utils.py
=> Date time slider

gemviz23/demo/mainwindow.py, gemviz23/resultswindow.py, gemviz23/resultswindow_tablemodel.py, gemviz23/resultwindow.ui
=> Results window connected to tiled

gemviz23/demo/mainwindow.py, gemviz23/demo/resources/filterpanel.ui, gemviz23/demo/resources/mainwindow.ui
=> work for refactor the filterpanel UI #49

gemviz23/demo/resultwindow.py
=> Handles unexpected metadata results

gemviz23/demo/resources/resultwindow.ui
=> select entire row 

gemviz23/demo/resultwindow.py
=> save QComboBox size selection of user

gemviz23/demo/filterpanel.py, gemviz23/demo/resultwindow.py
=> able to refresh catalog using return key in a filter textBox

gemviz23/demo/filterpanel.py, gemviz23/demo/resources/filterpanel.ui, gemviz23/demo/resultwindow.py
=> use a filter catalog

gemviz23/demo/resultwindow.py
=> Generalize column labels & their access actions

gemviz23/demo/filterpanel.py, gemviz23/demo/resources/filterpanel.ui, gemviz23/demo/resultwindow.py
=> Able to filter using detector names and separate using " , "

gemviz23/demo/resources/vizpanel.ui, gemviz23/demo/resultwindow.py, gemviz23/demo/utils.py, gemviz23/demo/vizpanel.py
- close #78
This is a simple text view but it was easy to create.  Kinda slooowwww.
=> show some kind of data representation

env.yml
=> help create a conda environment

gemviz23/demo/filterpanel.py, gemviz23/demo/resultwindow.py
=> resolve problematic application crashes

gemviz23/demo/resultwindow.py
=> len(catalog) sometimes reported as 1

gemviz23/demo/mainwindow.py
=> do not crash app when chosen server cannot be opened

gemviz23/demo/date_time_range_slider.py, gemviz23/demo/filterpanel.py
=> allow run(s) on last date to appear in timeline

gemviz23/demo/utils.py
=> allow to match start time of last run

env.yml, gemviz23/demo/analyze_run.py, gemviz23/demo/filterpanel.py, gemviz23/demo/resources/vizpanel.ui, gemviz23/demo/resultwindow.py, gemviz23/demo/utils.py
=> identify the plottable data

gemviz/resultwindow.py
=> center column(s): Scan ID & #points

gemviz/resultwindow.py
=> show last run on last page

gemviz/resultwindow.py
=> refactor similar code to one method

gemviz/mainwindow.py
=> BUG #40 Fixes #40

gemviz/bluesky_runs_catalog_table_model.py
=> refactor of table columns with lambda

gemviz/bluesky_runs_catalog.py
- close #140 
Also removed unused argument (`pos`,`index`) and variable (`deadtime`)
=> Fixes splitter_moved

gemviz/mainwindow.py, gemviz/resources/mainwindow.ui, gemviz/tiledserverdialog.py
=> Add tiled server QcomboBox

.gitignore, MANIFEST.in, README.md, env.yml, gemviz/__init__.py, gemviz/aboutdialog.py, gemviz/analyze_run.py, gemviz/app.py, gemviz/app_settings.py, gemviz/bluesky_runs_catalog.py, gemviz/bluesky_runs_catalog_run_viz.py, gemviz/bluesky_runs_catalog_search.py, gemviz/bluesky_runs_catalog_table_model.py, gemviz/bluesky_runs_catalog_table_view.py, gemviz/date_time_range_slider.py, gemviz/licensedialog.py, gemviz/mainwindow.py, gemviz/range_slider.py, gemviz/resources/bluesky_runs_catalog_search.ui, gemviz/resources/date_time_range_slider.ui, gemviz/tiledserverdialog.py, gemviz/utils.py, pyproject.toml
=> make this package installable by pip

gemviz/app.py
=> support command-line options: help & version

gemviz/bluesky_runs_catalog_table_model.py
=> Mark unsuccessful runs with different background color in table

gemviz/aboutdialog.py, gemviz/analyze_run.py, gemviz/app.py, gemviz/bluesky_runs_catalog.py, gemviz/bluesky_runs_catalog_search.py, gemviz/bluesky_runs_catalog_table_model.py, gemviz/mainwindow.py, gemviz/range_slider.py, gemviz/user_settings.py, gemviz/utils.py
- close #105
command-line help now shows:
```bash
$ gemviz -h
usage: gemviz [-h] [--log {critical,fatal,error,warn,warning,info,debug,notset}] [-v]
gemviz: Python Qt5 application to visualize Bluesky data from tiled server.
options:
-h, --help            show this help message and exit
--log {critical,fatal,error,warn,warning,info,debug,notset}
Provide logging level. Example '--log debug'. Default level: 'warning'
-v, --version         show program's version number and exit
```
=> print() --> logger.debug (mostly)

env.yml
=> do not install tiled from conda-forge now

gemviz/bluesky_runs_catalog.py
=> made change so that if status is add, status becomes replace

gemviz/bluesky_runs_catalog_table_model.py, gemviz/bluesky_runs_catalog_table_view.py
=> Center column via role instead of delegate

env.yml, gemviz/chartview.py, gemviz/select_stream_fields.py, gemviz/tapi.py, gemviz/tests/test_chartview.py, pyproject.toml
=> refactor from pyqtgraph to matplotlib
